ARDUINO_DIR 	= /home/gose/arduino-1.5.8
ARDMK_DIR	= ./arduino-mk
AVR_TOOLS_DIR	= /usr

BOARD_TAG	= yun
ARDUINO_PORT	= /dev/ttyACM0
ARDUINO_LIBS	= Wire Wire/utility Scheduler OptoIn PIDuinoTasks cADC thermocouple TempMonitor PWM16 PID mcEEPROM Settings StatusLED
USER_LIB_PATH	= ./libraries

MONITOR_BAUDRATE	= 57600

include ./arduino-mk/Arduino.mk
