ARDUINO_DIR 	= /usr/share/arduino
ARDMK_DIR	= ./arduino-mk
AVR_TOOLS_DIR	= /usr

BOARD_TAG	= uno
ARDUINO_PORT	= /dev/ttyACM0
ARDUINO_LIBS	= Wire Wire/utility Scheduler OptoIn PIDuinoTasks cADC thermocouple TempMonitor PWM16
USER_LIB_PATH	= ./libraries

MONITOR_BAUDRATE	= 57600

include ./arduino-mk/Arduino.mk
